### ISSUE TITLE
Switching editor tabs does not call _update_mode

### ISSUE THREAD

**Issue by Rob23oba** [L4Vo5/i-wanna-lockpick-editor#2]
Switching editor tabs does not call `_update_mode` causing you to be stuck placing doors.

**How to reproduce:**
1. Try to go to the key tab.
2. Hover over the editor area.
3. The hover shows doors even though we've changed to the key editor.

**Explanation:**
Uh, no idea seems like `unbind` does weird stuff.

**Fix:**
editor.gd
```gdscript
func _ready() -> void:
	# ...

	# previously
	side_tabs.tab_changed.connect(_update_mode.unbind(1))

	# fix
	side_tabs.tab_changed.connect(_update_mode)

	# ...
```
... that works, for some reason

**Comment by L4Vo5** [comment]
Damn you're right. Thankfully it does work on the latest *released* version. I'll look into it when I actually get back into this project, since I was mid-changing how some things in the editor work. It's possible _update_mode used to have an extra argument or something

**Comment by L4Vo5** [comment]
Alright, so the cause is that I replaced the default TabContainer with a custom class called BookmarkTabContainer, and I implemented the `tab_changed` signal, but unlike with the default TabContainer, I didn't make that signal also emit the new tab index, so unbinding was unnecessary.
Anyways just fixed it in https://github.com/L4Vo5/i-wanna-lockpick-editor/commit/a2460a58093424e91f659b573f6921da1ae34249
